name: Unit Tests & Coverage 

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y cmake libpcre2-dev clang lcov libcunit1-dev libjansson-dev valgrind

    - name: Configure
      run: cmake -DCOVERAGE=ON -DBUILD_TESTS=ON .

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Coverage
      run: make coverage

    - name: Generate Coverage Report
      run: lcov --directory . --capture --output-file coverage.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ${{github.workspace}}/coverage.info

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
