name: Doxygen

# Only run on main
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    if: ${{ github.event_name != 'pull_request' }} # and never, ever run on pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install cmake zlib1g-dev libpcre2-dev clang lcov libcunit1-dev doxygen libjansson-dev

    - name: Configure CMake
      run: cmake -DBUILD_DOC=ON .

    - name: Get Doxygen awesome CSS
      run: ./misc/setup_doxycss.sh

    - name: Build Doc
      run: make

    - name: Configure Pages
      uses: actions/configure-pages@v5

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/html/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
